-- Canarias Accesible Suite · esquema inicial de laboratorio
create extension if not exists pgcrypto;
create table profiles (id uuid primary key references auth.users(id) on delete cascade, full_name text not null, role text not null check(role in ('admin','gestion','tecnico','consulta')), technician_code text, active boolean default true, created_at timestamptz default now());
create table clients (id uuid primary key default gen_random_uuid(), legacy_code text unique, name text not null, contact_name text, phone text, created_at timestamptz default now(), updated_at timestamptz default now());
create table installations (id uuid primary key default gen_random_uuid(), legacy_installation text unique, client_id uuid references clients(id), address text, street text, postal_code text, municipality text, province text, model text, article_code text, article_description text, technician_code text, lat double precision, lng double precision, coordinate_source text default 'pending', coordinate_locked boolean default false, installed_at date, source_payload jsonb default '{}'::jsonb, created_at timestamptz default now(), updated_at timestamptz default now());
create table jobs (id uuid primary key default gen_random_uuid(), installation_id uuid references installations(id), assigned_to uuid references profiles(id), job_type text not null check(job_type in ('instalacion','reparacion','mantenimiento','revision')), status text not null default 'pendiente' check(status in ('pendiente','en_curso','finalizado','revisado','cancelado')), scheduled_at timestamptz, priority text default 'normal', notes text, created_by uuid references profiles(id), created_at timestamptz default now(), updated_at timestamptz default now());
create table reports (id uuid primary key default gen_random_uuid(), job_id uuid references jobs(id), technician_id uuid references profiles(id), form_data jsonb not null default '{}'::jsonb, client_signature_path text, completed_at timestamptz, sync_origin text default 'online', created_at timestamptz default now(), updated_at timestamptz default now());
create table attachments (id uuid primary key default gen_random_uuid(), report_id uuid references reports(id) on delete cascade, installation_id uuid references installations(id), storage_path text not null, kind text default 'photo', metadata jsonb default '{}'::jsonb, created_at timestamptz default now());
create table audit_log (id bigint generated always as identity primary key, table_name text not null, record_id text not null, action text not null, actor_id uuid references profiles(id), old_data jsonb, new_data jsonb, created_at timestamptz default now());
create index installations_technician_idx on installations(technician_code);create index jobs_assigned_status_idx on jobs(assigned_to,status);create index reports_job_idx on reports(job_id);
alter table profiles enable row level security;alter table clients enable row level security;alter table installations enable row level security;alter table jobs enable row level security;alter table reports enable row level security;alter table attachments enable row level security;
-- Las políticas RLS definitivas se crearán después de confirmar los roles reales.
